spring:
  application:
    name: cards
build:
  version: 1.0
cards:
  message : "welcome to cards de Microservice Application"
  contactDetails:
    name: Saikat Sen
    email: saikatsenproject@gmail.com
  phNo:
    - 1234567890
    - 1234567897
