spring:
  application:
    name: loans
build:
  version: 1.0
loans:
  message : "welcome to loans prod Microservice Application"
  contactDetails:
    name: Saikat Sen
    email: saikatsenproject@gmail.com
  phNo:
    - 1234567890
    - 1234567897