server:
  port: 9000
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3309/loansDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"