spring:
  application:
    name: accounts
build:
  version: 1.2
accounts:
  message : "welcome to Prod Microservice Application"
  contactDetails:
    name: Saikat Sen
    email: saikatsenproject@gmail.com
  phNo:
    - 1234567890
    - 1234567897