spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:microServiceDB
    username: saikat
    password: saikat
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_dev.yaml"
      - "application_prod.yaml"
  profiles:
    active: dev
build:
  version: 1.0

accounts:
  message : "welcome to Microservice Application"
  contactDetails:
    name: Saikat Sen
    email: saikatsenproject@gmail.com
  phNo:
    - 1234567890
    - 1234567897