## This docker compose use to create how different microservice connect
## with each other and run.Docker will create the container base on serial no.
## But the diffeculties is it will throw an exception while create a ccounts,loans,
## cards because it's directly depends on config server start.

## docker can't connect to external network port i.e 8081
## or 3308 within it's service

services:
#  rabbit:
#    image: "rabbitmq:4-management"
#    hostname: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: "rabbitmq-diagnostics check_port_connectivity"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service
  accountsDB:
    image: mysql
    container_name: accountsDB
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_DATABASE: accountsDB # V.V.I
      MYSQL_ROOT_PASSWORD: root
    extends:
      file: common-config.yml
      service: network-deploy-service
  cardsDB:
    image: mysql
    container_name: cardsDB
    ports:
      - 3310:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_DATABASE: cardsDB # V.V.I
      MYSQL_ROOT_PASSWORD: root
    extends:
      file: common-config.yml
      service: network-deploy-service
  loansDB:
    image: mysql
    container_name: loansDB
    ports:
      - 3309:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"] ## case sensitive
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_DATABASE: loansDB # V.V.I
      MYSQL_ROOT_PASSWORD: root
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
    image: "saikatsenproject/configserver:part4"
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
#    depends_on:
#      rabbit:
#        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
  accounts:
    image: "saikatsenproject/accounts:part4"
    container_name: accounts-ms
    ports:
      - 8081:8080
    depends_on:
      accountsDB:
          condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsDB:3306/accountsDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  cards:
    image: "saikatsenproject/cards:part4"
    container_name: cards-ms
    ports:
      - 8091:8090
    depends_on:
      cardsDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsDB:3306/cardsDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  loans:
    image: "saikatsenproject/loans:part4"
    container_name: loans-ms
    ports:
      - 9001:9000
    depends_on:
      loansDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansDB:3306/loansDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  microservice:
    driver: "bridge"