server:
  port: 8090
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:microServiceDB
    username: saikat
    password: saikat
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true